### Introduction to Tensors

In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

In [2]:
import tensorflow as tf
import numpy as np

In [3]:
rank_0_tensor = tf.constant(5)

In [4]:
print(rank_0_tensor) # rank zero

tf.Tensor(5, shape=(), dtype=int32)


In [5]:
# rand one

rank_1_tensor = tf.constant([2.0,4.0,5.0])
print(rank_1_tensor)

tf.Tensor([2. 4. 5.], shape=(3,), dtype=float32)


In [6]:
rank_2_tensor = tf.constant([[1,2],
                            [3,4],
                            [5,6]], dtype = tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


In [7]:
rank_3_tensor = tf.constant([
    [[0,1,2,3,4],
    [5,6,7,8,9]],
    [[10,11,12,13,14],
    [15,16,17,18,19]],
    [[20,21,22,23,24],
    [25,26,27,28,28]],
])

print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 28]]], shape=(3, 2, 5), dtype=int32)


In [8]:
# converting a tensor to Numpy array

rank_2_tensor.numpy()

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

In [9]:
a = tf.constant([[1,2],
                [3,4]])
b = tf.constant([[1,1],
                [1,1]])

In [14]:
print(tf.add(a,b), "\n")
print(tf.multiply(a,b), "\n")  # element wise multiplication
print(tf.matmul(a,b))  # matrix multiplication

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32)


In [11]:
type(rank_1_tensor)

tensorflow.python.framework.ops.EagerTensor

In [12]:
type(rank_2_tensor)

tensorflow.python.framework.ops.EagerTensor

In [15]:
c = tf.constant([[4.0,5.0],
                [10.0,1.0]])

In [19]:
# initializing the tensor
tf.reduce_max(c)  # gives max value

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>

In [22]:
print(tf.math.argmax(c))  # returns the index of maximum value

tf.Tensor([1 0], shape=(2,), dtype=int64)


In [23]:
print(tf.nn.softmax(c)) 
# computes the probability distribution over the elements of c.

tf.Tensor(
[[2.6894143e-01 7.3105854e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


In [24]:
# broadcasting the variables

In [25]:
x = tf.constant([1,2,3])
y = tf.constant(2)
z = tf.constant([2,2,2])

In [30]:
print(tf.multiply(x,2))

tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [32]:
print(x*y)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [33]:
print(x*z)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [34]:
print(y*z)

tf.Tensor([4 4 4], shape=(3,), dtype=int32)


In [35]:
# reshaping
x = tf.constant([[1],[2],[3]])

In [38]:
print(x.shape)

(3, 1)


In [39]:
reshaped = tf.reshape(x,[1,3])

In [40]:
print(x.shape)

(3, 1)


In [41]:
print(reshaped.shape)

(1, 3)


In [43]:
print(reshaped)

tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)


In [44]:
print(x)

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)


##### Different Types of Tensors

- Ragged Tensor: Tensor with the variable number of elements along some axes is called Ragged Tensor

In [46]:
ragged_list = [
    [0,1,2,3],
    [4,5],
    [6,7,8],
    [9]]

In [49]:
ragged_list

[[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]

In [50]:
ragged_tensor = tf.ragged.constant(ragged_list)

In [51]:
ragged_tensor

<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>

- Scalar String Tensor: It is a datatype, which means that data can be represented as strings (variable-length byte arrays) in Tensors

In [53]:
scalar_string_tensor = tf.constant("gray wolf")

In [54]:
print(scalar_string_tensor)

tf.Tensor(b'gray wolf', shape=(), dtype=string)


We can see that we can even represent the strings as Tensors.